### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by prjemian** [nexusformat/cnxvalidate#16] opened 2016-10-12 13:53 UTC
After compiling, `nxvtest` failed on the first test:

```
mintadmin@mintadmin-VirtualBox ~/.../cnxvalidate/build $ make test
Running tests...
Test project /home/mintadmin/Documents/eclipse/NeXus/cnxvalidate/build
    Start 1: nxvtest
1/1 Test #1: nxvtest ..........................***Failed    0.28 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.28 sec

The following tests FAILED:
      1 - nxvtest (Failed)
Errors while running CTest
make: *** [test] Error 8 
```

Here is the output when compiling:

```
mintadmin@mintadmin-VirtualBox ~/.../NeXus/cnxvalidate $ cd build/
mintadmin@mintadmin-VirtualBox ~/.../cnxvalidate/build $ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- /home/mintadmin/Documents/eclipse/NeXus/cnxvalidate
-- /home/mintadmin/Documents/eclipse/NeXus/cnxvalidate/cmake_include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mintadmin/Documents/eclipse/NeXus/cnxvalidate/build
mintadmin@mintadmin-VirtualBox ~/.../cnxvalidate/build $ make
Scanning dependencies of target NXV_Static_Library
[  4%] Building C object src/CMakeFiles/NXV_Static_Library.dir/nxvmainloop.c.o
[  8%] Building C object src/CMakeFiles/NXV_Static_Library.dir/nxvcontext.c.o
[ 13%] Building C object src/CMakeFiles/NXV_Static_Library.dir/hash.c.o
[ 17%] Building C object src/CMakeFiles/NXV_Static_Library.dir/nxdlutil.c.o
[ 21%] Building C object src/CMakeFiles/NXV_Static_Library.dir/nxvgroup.c.o
[ 26%] Building C object src/CMakeFiles/NXV_Static_Library.dir/nxvfield.c.o
[ 30%] Building C object src/CMakeFiles/NXV_Static_Library.dir/nxvutil.c.o
Linking C static library libnxvalidate.a
[ 30%] Built target NXV_Static_Library
Scanning dependencies of target nxvalidate
[ 34%] Building C object CMakeFiles/nxvalidate.dir/nxvmain.c.o
Linking C executable nxvalidate
[ 34%] Built target nxvalidate
Scanning dependencies of target NXV_Shared_Library
[ 39%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/nxvmainloop.c.o
[ 43%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/nxvcontext.c.o
[ 47%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/hash.c.o
[ 52%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/nxdlutil.c.o
[ 56%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/nxvgroup.c.o
[ 60%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/nxvfield.c.o
[ 65%] Building C object src/CMakeFiles/NXV_Shared_Library.dir/nxvutil.c.o
Linking C shared library libnxvalidate.so
[ 65%] Built target NXV_Shared_Library
Scanning dependencies of target nxvtest
[ 69%] Building CXX object test/CMakeFiles/nxvtest.dir/testbasics.cpp.o
[ 73%] Building CXX object test/CMakeFiles/nxvtest.dir/testmain.cpp.o
[ 78%] Building CXX object test/CMakeFiles/nxvtest.dir/testutil.cpp.o
/home/mintadmin/Documents/eclipse/NeXus/cnxvalidate/test/testutil.cpp: In function \u2018void TestLogger(hash_table*, void*)\u2019:
/home/mintadmin/Documents/eclipse/NeXus/cnxvalidate/test/testutil.cpp:44:51: warning: deprecated conversion from string constant to \u2018char*\u2019 [-Wwrite-strings]
  dataPath = (char *)hash_lookup("dataPath",logData);
                                                   ^
[ 82%] Building CXX object test/CMakeFiles/nxvtest.dir/testgroup.cpp.o
[ 86%] Building CXX object test/CMakeFiles/nxvtest.dir/testlink.cpp.o
[ 91%] Building CXX object test/CMakeFiles/nxvtest.dir/testunidim.cpp.o
[ 95%] Building CXX object test/CMakeFiles/nxvtest.dir/testsimpleatt.cpp.o
[100%] Building CXX object test/CMakeFiles/nxvtest.dir/testdepends.cpp.o
Linking CXX executable nxvtest
[100%] Built target nxvtest
```

**Comment by mkoennecke** [comment] 2017-10-30 10:47
I failed to reproduce this. Can you run nxvtest in the test directory after the build in order to see where the test fails?

**Comment by mkoennecke** [comment] 2020-10-20 09:20
As this has not been reproduced and works for me on a variety of platforms, I close this.

**Closed by mkoennecke** 2020-10-20 09:20 UTC
Labels: bug
