### ISSUE TITLE
test of nxvalidate on linuxmint

### ISSUE THREAD

**Issue by prjemian** [nexusformat/cnxvalidate#12] opened 2016-05-12 01:40 UTC
Built on linuxmint 17.3 system, here are the results when testing an example file from the NeXus manual:

	mintadmin@mintadmin-VirtualBox ~/.../NeXus/cnxvalidate/build $ ./nxvalidate /home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5
	message="Missing required global file_name attribute" sev=error dataPath=/ dataFile=/home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5 
	message="Missing required global file_time attribute" sev=error dataPath=/ dataFile=/home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5 
	message="Wrong root group class ???, expected NXentry" dataPath=/entry sev=error dataFile=/home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5 
	message="Cannot validate entry, failed to find application definition" dataPath=/entry sev=error dataFile=/home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5 
	3 errors and 0 warnings found when validating /home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5

1. Not sure about the "Missing required global file_name/ file_time attribute" errors.  Are there any *required* global attributes?
1. root group class is NXentry (see below)
1. test file uses no application definition, should be able to validate the file anyway

test data file structure:

	/home/mintadmin/Documents/eclipse/NeXus/definitions/manual/source/examples/h5py/writer_2_1.hdf5 : NeXus data file
	  entry:NXentry
		@NX_class = NXentry
		data:NXdata
		  @NX_class = NXdata
		  @signal = counts
		  @axes = two_theta
		  @two_theta_indices = [0]
		  counts --> /entry/instrument/detector/counts
		  two_theta --> /entry/instrument/detector/two_theta
		instrument:NXinstrument
		  @NX_class = NXinstrument
		  detector:NXdetector
			@NX_class = NXdetector
			counts:NX_INT32[31] = [1037, 1318, 1704, '...', 1321]
			  @units = counts
			  @target = /entry/instrument/detector/counts
			two_theta:NX_FLOAT64[31] = [17.926079999999999, 17.925909999999998, 17.925750000000001, '...', 17.92108]
			  @units = degrees
			  @target = /entry/instrument/detector/two_theta

**Comment by mkoennecke** [comment] 2016-05-18 12:13
I will look at the not recognized NXentry when I get down to it. 

If cnxvalidate should verify files without an application definition is really a question on the scope 
of cnxvalidate. Then, in some stage we had a total application definition which encompassed everything. Validating against that while switching off some warnings on optional content might do the trick.

**Comment by mkoennecke** [comment] 2016-05-19 10:00
I now have looked into this somewhat. The problem appears to be with the function  H5LTget_attribute_string() from HDF5 which I use to read the NX_class attribute. When you use: 

nxentry.attrs['NX_class'] = numpy.string_('NXentry')

(the recommended way for portable strings in h5py) then everything is fine. 

If you use:

nxentry.attrs['NX_class'] = 'NXentry'

then h5py generates a variable length string. H5LTget_attribute_string() returns success when reading this but the data read back is rubbish. Which in turn makes cnxvalidate complain bitterly. 

I now have reported the issue to the HDF5 people. I will wait now for their response before I decide how to proceed with this.

**Comment by prjemian** [comment] 2016-05-19 19:15
Your suggestion, to write string attributes will be built into the next release of spec2nexus.eznx.  Other developers may also follow this suggestion.  

Is it to be expected that we can influence all possible writers of HDF5 files to limit the way they write strings to our recommended methods?  Seems we are being compelled by the community to expand what is acceptable.

**Comment by prjemian** [comment] 2016-05-19 19:18
I hope that validating any NeXus HDF5 data file, whether with or without use of one or more application definitions, will become within the scope of this application, if it is not already.

**Comment by rayosborn** [comment] 2016-05-19 19:34
The problem with using `numpy.string_` is that it makes it impossible to change the class of a group to a longer name after the file has been written, so I would strongly resist making it another requirement of NeXus files. There obviously is an HDF5 routine for reading variable length string attributes, so hopefully the HDF5 team will respond soon.

**Comment by zjttoefs** [comment] 2016-05-20 07:44
Specifically for NX_class I must admit that I never saw the need of updating that after it had been written.

However you can always update, remove, replace datasets and attributes in h5py (or any other HDF5 API). numpy.string_ does not stop you doing so.

**Comment by mkoennecke** [comment] 2016-05-20 08:40
Like Tobias, I do not see the point in rewriting the NX_class attribute.

I now have feedback from the HDF5 people: it is indeed a fact that H5LTget_attribute_string() behaves differently when reading variable length strings versus normal strings. The difference in behavior is not documented. It is considered a bug. I can solve the problem by providing a wrapper function which fixes the problem.  

But then, when we as experts encounter these issues, how would mere mortal NeXus users fare when they try to read NeXus files and have to account for those variable length  strings? Allowing variable length strings makes reading strings more complex. Thus I pose the question if we really want to allow them in NeXus? Especially as they seem to be badly documented by the HDF people themselves and are an advanced HDF5 subject.

**Comment by zjttoefs** [comment] 2016-05-20 11:20
This is a case where our normal abstraction of the backend breaks down a bit.
We don't say what your chunking needs to be or how you want to lay out your VDS. But in those cases the HDF5 works in your favour and you actually don't need to care while reading.
For strings the HDF group have created a bit of a mess and we, as a standard, would like reading to be simple. 

Before enforcing one way or the other, we should to consider people using h5py or other non-broken APIs. For them writing variable length strings may be the normal thing to do. In the case of h5py even without realising. And reading isn't an issue for them either. 

Even with a rule to use fixed lengths the default is powerful and people will use it. SasView will read it. Good programmers will be generous in accepting any parseable input. So my idea would to accept either and hope for a better HDF5 string API.

**Comment by rayosborn** [comment] 2016-05-20 12:14
The problem is that, in Python 3, all strings are unicode, and the default is for h5py to write unicode as variable length strings. I don't think it's fair to call it an advanced subject. It's the natural way to do things in Python, where it works completely transparently. I'm a little puzzled why the 'NX_class' attribute is more difficult to read than other attributes. I thought you (@mkoennecke) had just solved the problem of reading variable length string attributes.

**Comment by mkoennecke** [comment] 2016-05-20 13:38
In some stage we decided to base cnxvalidate on the naked HDF5 API rather then NAPI. The variable length string thing is fixed in NAPI; now it would need to be fixed in cnxvalidate too. But I wanted to hear some opinion about the worth of having variable length  strings in NeXus beforehand. Because having them means:

- ANY reading code will have to check if the string under consideration is a variable length one or not.
- Call different HDF5 routines and use different data items  to read either normal strings or variable   length ones 

The question is: does the NIAC want to impose that complication on everyone?

Variable length strings may be a no issue with python; I cannot judge. What I can judge is that at the HDF5 side of the world, variable lengths strings have the look and feel of second class citizens. Hence the advanced usage label.

**Comment by mkoennecke** [comment] 2016-07-13 10:10
I modified cnxvalidate to accept variable length strings. I added a test with the writer_2.1.hdf5 file 
to confirm that it works. Thus I close this one now.

**Closed by mkoennecke** 2016-07-13 10:10 UTC
